on: [push]

jobs:
  get_okta_token:
    runs-on: ubuntu-latest
    name: Get Okta ASA token to upload file to a server
    steps:
      # Checkout my private repo
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: sudobinbash/okta-asa-github-action
          ref: main
          ssh-key: ${{ secrets.REPO_KEY }}
      - name: Get ephemeral keys from Okta
        uses: ./ 
        id: get-okta-keys
        with:
          service-account-key: ${{ secrets.ASA_ACCOUNT_KEY }}
          service-account-secret: ${{ secrets.ASA_ACCOUNT_SECRET }}
          asa-team: ${{ secrets.ASA_TEAM }}
          asa-project: ${{ secrets.ASA_PROJECT }}
          server-name: ${{ secrets.SERVER_NAME }}
      # Print outputs from the `get-okta-keys` step
      - name: Get outputs
        run: |
          echo "User id to SSH/SCP into the server: ${{ steps.get-okta-keys.outputs.ssh-user }}"
          echo "Ephemeral certificate for server access: ${{ steps.get-okta-keys.outputs.ssh-certificate }}"
          echo "Ephemeral private key for server access: ${{ steps.get-okta-keys.outputs.ssh-private-key }}"
          echo "Ephemeral public key for server access: ${{ steps.get-okta-keys.outputs.ssh-public-key }}"
          echo "Ephemeral private key fingerprint: ${{ steps.get-okta-keys.outputs.ssh-fingerprint }}"
          echo "IP to SSH/SCP into the server: ${{ steps.get-okta-keys.outputs.ssh-ip }}"
          echo "port to SSH/SCP into the server: ${{ steps.get-okta-keys.outputs.ssh-port }}"
      - name: Transfer repo files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ steps.get-okta-keys.outputs.ssh-ip }}
          port: ${{ steps.get-okta-keys.outputs.ssh-port }}
          key: ${{ steps.get-okta-keys.outputs.ssh-certificate }}
          username: ${{ steps.get-okta-keys.outputs.ssh-user }}
          source: "sample/*"
          target: "sample"